"""
This YAML file is used for defining a GitHub Actions workflow named "check-models". It is located in the ".github/workflows" directory of the project.

The purpose of this workflow is to perform checks on models used in the project, save the report as a csv and then upload result into validation checks on scivison website.

Please refer to the contents of the file for more specific details on the steps and configurations used in this workflow.
"""


name: Check models
on: push
  # schedule:
  #   - cron:  '18 3 * * *'
    
jobs:
  check-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Scivision
        run: pip install -e .
      - name: Check model catalog
        run: scivision-check-models
      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: check-models-report
          path: check_models.csv
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: model-checks-report-latest-release
          name: Models checks report
          commit: ${{ github.ref }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: check_models.js
